// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $CloseButtonModal from "./islands/CloseButtonModal.tsx";
import * as $CreateStoreForm from "./islands/CreateStoreForm.tsx";
import * as $CreateStoreModal from "./islands/CreateStoreModal.tsx";
import * as $FlexibleButtons from "./islands/FlexibleButtons.tsx";
import * as $HeroCard from "./islands/HeroCard.tsx";
import * as $HeroInfo from "./islands/HeroInfo.tsx";
import * as $HeroTab from "./islands/HeroTab.tsx";
import * as $HeroTimeButtons from "./islands/HeroTimeButtons.tsx";
import * as $HeroWithTime from "./islands/HeroWithTime.tsx";
import * as $PricesButtons from "./islands/PricesButtons.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
  },
  islands: {
    "./islands/CloseButtonModal.tsx": $CloseButtonModal,
    "./islands/CreateStoreForm.tsx": $CreateStoreForm,
    "./islands/CreateStoreModal.tsx": $CreateStoreModal,
    "./islands/FlexibleButtons.tsx": $FlexibleButtons,
    "./islands/HeroCard.tsx": $HeroCard,
    "./islands/HeroInfo.tsx": $HeroInfo,
    "./islands/HeroTab.tsx": $HeroTab,
    "./islands/HeroTimeButtons.tsx": $HeroTimeButtons,
    "./islands/HeroWithTime.tsx": $HeroWithTime,
    "./islands/PricesButtons.tsx": $PricesButtons,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
