// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $CreateStoreModal from "./islands/CreateStoreModal.tsx";
import * as $HeaderInitialButtons from "./islands/HeaderInitialButtons.tsx";
import * as $HeroCard from "./islands/HeroCard.tsx";
import * as $HeroTab from "./islands/HeroTab.tsx";
import * as $HeroWithTime from "./islands/HeroWithTime.tsx";
import * as $PricesButtons from "./islands/PricesButtons.tsx";
import * as $TalkModal from "./islands/TalkModal.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/CreateStoreModal.tsx": $CreateStoreModal,
    "./islands/HeaderInitialButtons.tsx": $HeaderInitialButtons,
    "./islands/HeroCard.tsx": $HeroCard,
    "./islands/HeroTab.tsx": $HeroTab,
    "./islands/HeroWithTime.tsx": $HeroWithTime,
    "./islands/PricesButtons.tsx": $PricesButtons,
    "./islands/TalkModal.tsx": $TalkModal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
